services:
  sh.repository.user:
      class: ScavengerWebserviceBundle\Entity\UserRepository
      factory_service: doctrine.orm.default_entity_manager
      factory_method: getRepository
      arguments:
        - 'ScavengerWebserviceBundle:User'